

spring:
  thymeleaf:
    mode: HTML
    cache: false

  profiles:
    active: pro
  messages:
    basename: i18n/messages

comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png
server:
  port: 9000